server:
  #配置端口
  port: 80
spring:
  thymeleaf:
      mode: LEGACYHTML5
      #关闭thymeleaf缓存
      cache: false
      #配置模版位置
      prefix: classpath:/templates/
      #配置模版后缀
      suffix: .html
  profiles:
    #配置使用的配置文件
    active: dev
mybatis:
  #定义mybatis的xml文件位置
  mapper-locations: mybatis/**/*Mapper.xml